# Generated by Django 2.1.3 on 2018-11-10 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('content', models.TextField(max_length=500, verbose_name='内容')),
                ('level', models.IntegerField(choices=[(1, '重要，紧急'), (2, '重要，不紧急'), (3, '不重要，紧急'), (4, '不重要，不紧急'), (5, '随便')], default=5)),
                ('finish_level', models.IntegerField(choices=[(0, '未完成'), (1, '完美'), (2, '优秀'), (3, '良好'), (4, '及格'), (5, '不理想')], default=0)),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '代办事项',
                'verbose_name_plural': '代办事项',
            },
        ),
    ]
